baseURL = "http://example.org/"
languageCode = "en-us"
title = "Sandesign3d"
disableKinds = ["taxonomyTerm"]

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "3D Druck"
url = "/3d-druck/"
weight = 10

[[menu.main]]
name = "CAD"
url = "/cad/"
weight = 20

[[menu.main]]
name = "Kontakt"
url = "/kontakt/"
weight = 30
